services:
  evals:
    image: adalmia/sensai-evals:latest
    container_name: evals
    ports:
      - "5001:5001"
    environment:
      - ENV=production
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5001/login" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - /appdata_prod:/appdata
  cron:
    image: adalmia/sensai-evals:latest
    container_name: evals-data-sync-cron
    restart: unless-stopped
    volumes:
      - /appdata_prod:/appdata
    command: sh -c "echo '0 8 * * * cd /app && python -m src.cron' | crontab - && cron -f"
