services:
  sensai-evals:
    image: adalmia/sensai-evals:latest
    container_name: sensai-evals
    ports:
      - "5001:5001"
    environment:
      - ENV=production
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5001/login" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - /appdata_prod:/appdata
