services:
  evals:
    image: adalmia/sensai-evals:latest
    container_name: evals
    ports:
      - "5001:5001"
    environment:
      - ENV=production
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5001/login" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - /appdata_prod:/appdata

  cron:
    image: adalmia/sensai-evals:latest
    container_name: evals-data-sync-cron
    restart: unless-stopped
    environment:
      - S3_LLM_TRACES_KEY=${S3_LLM_TRACES_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - TZ=Asia/Kolkata
    volumes:
      - /appdata_prod:/appdata
    command: sh -c "echo '#!/bin/bash' > /app/cron_script.sh && echo 'export S3_LLM_TRACES_KEY=${S3_LLM_TRACES_KEY}' >> /app/cron_script.sh && echo 'export S3_BUCKET_NAME=${S3_BUCKET_NAME}' >> /app/cron_script.sh && echo 'cd /app/src' >> /app/cron_script.sh && echo '/usr/local/bin/python -m cron' >> /app/cron_script.sh && chmod +x /app/cron_script.sh && echo '0 8 * * * /app/cron_script.sh >> /appdata/logs/evals-cron.log 2>&1' | crontab - && cron -f"
