name: Deploy to EC2

# Only run on manual trigger
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            adalmia/sensai-evals:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          script: |            
            # Navigate to app directory
            cd sensai-evals && sudo docker compose -f docker-compose.yml pull && sudo docker compose -f docker-compose.yml up -d

      - name: Verify deployment
        run: |
          echo "Deployment completed for environment: ${{ github.event.inputs.environment }}"
          echo "Image tags pushed:"
          echo "- adalmia/sensai-evals:latest"
          echo "- adalmia/sensai-evals:${{ github.sha }}" 